# Generated by Django 4.1.2 on 2022-10-10 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_managers_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=datetime.datetime(2022, 10, 10, 7, 28, 43, 45300, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
