# Generated by Django 4.1.2 on 2022-10-10 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
