# Generated by Django 4.1.2 on 2022-10-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
