# Generated by Django 4.1.2 on 2022-10-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
